(define (Entity dna port name glyph z y x)
 (define (self msg) (eval msg))
 (define oz z)
 (define oy y)
 (define ox x)
 (define (setPort port0)
   (set! port port0))
 (define (setName name0)
   (set! name name0))
 (define (setGlyph glyph0)
   (set! glyph glyph0))
 (define (setLoc z0 y0 x0)
   (set! oz z) (set! oy y) (set! ox x)
   (set! z z0) (set! y y0) (set! x x0))
 (define (gps)
   (list z y x))
 self)
